import { StyleSheet } from "react-native";

import { colors, type AppColors } from "./colors";

export function createStyles(colors: AppColors) {
  return StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  appShell: { flex: 1, backgroundColor: colors.background, paddingTop: 8 },
  header: {
    height: 62,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: colors.outline,
    backgroundColor: colors.background,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between"
  },
  brand: { flexDirection: "row", alignItems: "center", gap: 10 },
  logoMark: {
    width: 36,
    height: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.primaryOutline,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primarySoft
  },
  logoText: { color: colors.text, fontSize: 17, lineHeight: 20, fontWeight: "800" },
  logoCaption: { color: colors.muted, fontSize: 10, lineHeight: 13, fontWeight: "600" },
  headerActions: { flexDirection: "row", alignItems: "center", gap: 12 },
  iconButton: {
    width: 38,
    height: 38,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.secondaryOutline,
    backgroundColor: colors.secondarySoft
  },
  content: { flex: 1 },
  screenContent: { paddingHorizontal: 20, paddingTop: 24, paddingBottom: 122, gap: 24 },
  homeHero: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.primaryOutline,
    backgroundColor: colors.surface,
    padding: 20,
    gap: 12,
    overflow: "hidden"
  },
  heroIconRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  heroIcon: { width: 32, height: 32, borderRadius: 7, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center" },
  heroEyebrow: { color: colors.secondary, fontSize: 11, fontWeight: "800", textTransform: "uppercase" },
  homeHeroTitle: { maxWidth: "92%", color: colors.text, fontSize: 27, lineHeight: 34, fontWeight: "800" },
  homeHeroBody: { maxWidth: "94%", color: colors.muted, fontSize: 14, lineHeight: 21 },
  searchPanel: {
    minHeight: 58,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.primaryOutline,
    backgroundColor: colors.surface,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    gap: 12
  },
  searchInput: { flex: 1, color: colors.text, fontSize: 16 },
  searchClearButton: { width: 36, height: 36, borderRadius: 8, alignItems: "center", justifyContent: "center", backgroundColor: colors.secondarySoft },
  aiStatus: { flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 4 },
  pulseAnchor: { width: 32, height: 32, alignItems: "center", justifyContent: "center" },
  pulseRing: { position: "absolute", width: 32, height: 32, borderRadius: 16, backgroundColor: colors.primary },
  pulseDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: colors.primary },
  overline: { color: colors.muted, fontSize: 11, fontWeight: "900", letterSpacing: 1.2, textTransform: "uppercase" },
  overlinePrimary: { color: colors.primary, fontSize: 11, fontWeight: "900", letterSpacing: 1, textTransform: "uppercase" },
  statusLine: { height: 1, flex: 1, backgroundColor: colors.primaryOutline },
  titleRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  sectionTitleText: { color: colors.text, fontSize: 20, fontWeight: "900" },
  chipWrap: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  chip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.primaryOutline,
    backgroundColor: colors.surfaceGlass,
    paddingHorizontal: 16,
    paddingVertical: 10
  },
  chipText: { color: colors.text, fontSize: 13, fontWeight: "800" },
  selectedChip: { borderColor: colors.primary, backgroundColor: colors.primarySoft },
  sectionHeader: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", gap: 12 },
  bodyMuted: { color: colors.muted, fontSize: 13, lineHeight: 19 },
  linkText: { color: colors.primary, fontSize: 13, fontWeight: "800" },
  linkButton: { minHeight: 44, paddingHorizontal: 4, alignItems: "center", justifyContent: "center" },
  horizontalList: { gap: 14, paddingRight: 16 },
  screenshotCard: {
    width: 286,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: colors.primaryOutline,
    backgroundColor: colors.surfaceGlassHigh,
    shadowColor: "#000000",
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 2
  },
  compactScreenshot: { width: 230 },
  previewGradient: { height: 164, padding: 18, justifyContent: "space-between" },
  previewImage: { height: 164, width: "100%", backgroundColor: colors.surfaceHigh },
  previewTopLine: { height: 5, width: "42%", borderRadius: 99, backgroundColor: "rgba(255,255,255,0.78)" },
  previewRows: { gap: 8 },
  previewRow: { height: 8, borderRadius: 99, backgroundColor: "rgba(255,255,255,0.38)" },
  screenshotFooter: { minHeight: 66, padding: 14, flexDirection: "row", alignItems: "center", gap: 12 },
  emptyGallery: {
    minHeight: 132,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.outline,
    backgroundColor: colors.surface,
    padding: 18,
    alignItems: "center",
    justifyContent: "center",
    gap: 8
  },
  emptyGalleryTitle: { color: colors.text, fontSize: 15, fontWeight: "900", textAlign: "center" },
  emptyGalleryBody: { color: colors.muted, fontSize: 13, lineHeight: 19, textAlign: "center" },
  mediaAccessCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.primaryOutline,
    backgroundColor: colors.surface,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12
  },
  mediaAccessIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: colors.primarySoft,
    alignItems: "center",
    justifyContent: "center"
  },
  accessButton: {
    minHeight: 38,
    borderRadius: 9,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary
  },
  accessButtonText: { color: colors.onPrimary, fontSize: 12, fontWeight: "900" },
  flexOne: { flex: 1 },
  cardTitle: { color: colors.text, fontSize: 16, fontWeight: "800" },
  cardBody: { color: colors.text, fontSize: 15, lineHeight: 22 },
  statGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  metricCard: {
    flexGrow: 1,
    flexBasis: "46%",
    minHeight: 104,
    borderRadius: 12,
    borderWidth: 1,
    borderLeftWidth: 3,
    borderColor: colors.outline,
    backgroundColor: colors.surface,
    padding: 16,
    justifyContent: "center"
  },
  metricLabel: { color: colors.muted, fontSize: 11, fontWeight: "900", letterSpacing: 0.5, textTransform: "uppercase" },
  metricValue: { fontSize: 25, fontWeight: "900", marginTop: 7 },
  askPanel: {
    minHeight: 54,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.primaryOutline,
    backgroundColor: colors.surfaceGlassHighest,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 18,
    gap: 10
  },
  askText: { flex: 1, color: colors.text, fontSize: 15, fontWeight: "800" },
  chatShell: { flex: 1, paddingHorizontal: 16, paddingBottom: 92 },
  chatShellKeyboard: { paddingBottom: 12 },
  chatList: { flex: 1 },
  chatContent: { paddingTop: 16, paddingBottom: 16, gap: 16 },
  datePill: {
    alignSelf: "center",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.outline,
    paddingHorizontal: 14,
    paddingVertical: 6,
    backgroundColor: colors.surfaceGlass
  },
  messageRow: { maxWidth: "88%", flexDirection: "row", gap: 10, alignItems: "flex-start" },
  userMessageRow: { alignSelf: "flex-end", flexDirection: "row-reverse" },
  messageIcon: { width: 36, height: 36, borderRadius: 12, alignItems: "center", justifyContent: "center" },
  botIcon: { backgroundColor: colors.primarySoft, borderWidth: 1, borderColor: colors.primaryOutline },
  userIcon: { backgroundColor: colors.surfaceGlassHighest, borderWidth: 1, borderColor: colors.outline },
  messageBubble: { borderRadius: 18, padding: 14, borderWidth: 1 },
  aiBubble: { borderTopLeftRadius: 5, borderColor: colors.outline, backgroundColor: colors.surfaceGlass },
  userBubble: { borderTopRightRadius: 5, borderColor: "transparent", backgroundColor: colors.primaryContainer },
  messageText: { color: colors.text, fontSize: 15, lineHeight: 22 },
  userMessageText: { color: colors.onPrimary, fontWeight: "800" },
  typingRow: { flexDirection: "row", gap: 10, alignItems: "center" },
  typingBubble: {
    borderRadius: 18,
    borderTopLeftRadius: 5,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: colors.surfaceGlass,
    flexDirection: "row",
    gap: 5
  },
  typingDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: colors.primary },
  chatComposer: {
    minHeight: 56,
    maxHeight: 104,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: colors.primaryOutline,
    backgroundColor: colors.surface,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 6,
    marginTop: 10,
    gap: 10
  },
  composerInput: { flex: 1, minHeight: 42, color: colors.text, fontSize: 15 },
  sendButton: { width: 34, height: 34, borderRadius: 17, alignItems: "center", justifyContent: "center", backgroundColor: colors.primary },
  sendButtonDisabled: { opacity: 0.42 },
  pageIntro: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 14 },
  pageIntroCopy: { flex: 1, minWidth: 0, gap: 4 },
  pageTitle: { color: colors.text, fontSize: 30, lineHeight: 36, fontWeight: "900" },
  primaryButton: {
    minHeight: 44,
    flexShrink: 0,
    borderRadius: 10,
    paddingHorizontal: 14,
    backgroundColor: colors.primary,
    flexDirection: "row",
    alignItems: "center",
    gap: 7
  },
  primaryButtonText: { color: colors.onPrimary, fontWeight: "900" },
  suggestionCard: { borderRadius: 12, borderWidth: 1, borderColor: colors.outline, backgroundColor: colors.surface, padding: 18, gap: 14 },
  suggestionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  badge: {
    alignSelf: "flex-start",
    overflow: "hidden",
    borderRadius: 999,
    color: colors.secondary,
    borderWidth: 1,
    borderColor: colors.secondaryOutline,
    backgroundColor: colors.secondarySoft,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 11,
    fontWeight: "900"
  },
  buttonRow: { flexDirection: "row", gap: 10 },
  secondaryButton: { borderRadius: 12, paddingHorizontal: 14, paddingVertical: 10, backgroundColor: colors.secondary },
  secondaryButtonText: { color: colors.onSecondary, fontWeight: "900" },
  subtleButton: {
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: colors.surfaceGlassHigh,
    borderWidth: 1,
    borderColor: colors.outline
  },
  subtleButtonText: { color: colors.text, fontWeight: "800" },
  actionNotice: {
    minHeight: 52,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.primaryOutline,
    backgroundColor: colors.primarySoft,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10
  },
  actionNoticeText: { flex: 1, color: colors.text, fontSize: 13, lineHeight: 19, fontWeight: "700" },
  collectionGrid: { flexDirection: "row", flexWrap: "wrap", gap: 14 },
  collectionItem: { width: "47%", gap: 10 },
  collectionFolder: {
    aspectRatio: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.outline,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
    gap: 12
  },
  collectionName: { color: colors.text, textAlign: "center", fontSize: 16, fontWeight: "800" },
  heroMetric: {
    minHeight: 290,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.outline,
    backgroundColor: colors.surface,
    padding: 18,
    justifyContent: "space-between"
  },
  heroMetricHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  bigNumber: { color: colors.primary, fontSize: 70, lineHeight: 76, fontWeight: "900" },
  barChart: { height: 86, flexDirection: "row", alignItems: "flex-end", gap: 8 },
  chartBar: { flex: 1, borderTopLeftRadius: 9, borderTopRightRadius: 9, backgroundColor: colors.primaryContainer },
  efficiencyCard: { borderRadius: 12, borderWidth: 1, borderColor: colors.outline, backgroundColor: colors.surface, padding: 18, gap: 18 },
  efficiencyRow: {
    borderBottomWidth: 1,
    borderBottomColor: colors.outline,
    paddingBottom: 14,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 14
  },
  efficiencyLabel: { fontSize: 16, fontWeight: "900" },
  efficiencyValue: { color: colors.text, fontSize: 24, fontWeight: "900" },
  activeCore: {
    minHeight: 130,
    borderRadius: 65,
    borderWidth: 1.5,
    borderColor: colors.primaryOutline,
    backgroundColor: colors.surfaceGlassHighest,
    alignItems: "center",
    justifyContent: "center",
    gap: 10
  },
  bottomNav: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 12,
    minHeight: 70,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.outline,
    backgroundColor: colors.surface,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    paddingHorizontal: 8,
    shadowColor: "#000000",
    shadowOpacity: 0.34,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12
  },
  navItem: { minWidth: 68, minHeight: 48, borderRadius: 22, alignItems: "center", justifyContent: "center", gap: 3, paddingHorizontal: 8 },
  activeNavItem: { backgroundColor: colors.primaryContainer },
  navLabel: { color: colors.muted, fontSize: 10, fontWeight: "900" },
  activeNavLabel: { color: colors.onPrimary },
  menuLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
    flexDirection: "row"
  },
  menuScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.42)"
  },
  sideMenu: {
    width: "78%",
    maxWidth: 330,
    height: "100%",
    borderRightWidth: 1,
    borderRightColor: colors.outline,
    backgroundColor: colors.surface,
    paddingHorizontal: 16,
    gap: 18
  },
  menuHeader: { flexDirection: "row", alignItems: "center", gap: 12 },
  menuTitle: { color: colors.text, fontSize: 24, lineHeight: 30, fontWeight: "900" },
  menuSubtitle: { color: colors.muted, fontSize: 12, lineHeight: 17, fontWeight: "700" },
  menuIconButton: {
    width: 36,
    height: 36,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: colors.outline,
    backgroundColor: colors.surfaceGlassHigh,
    alignItems: "center",
    justifyContent: "center"
  },
  menuSection: { gap: 10 },
  menuItem: {
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: colors.outline,
    backgroundColor: colors.surfaceGlass,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12
  },
  menuItemText: { color: colors.text, fontSize: 15, lineHeight: 20, fontWeight: "900" },
  themeToggle: {
    minHeight: 58,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: colors.primaryOutline,
    backgroundColor: colors.surfaceGlassHighest,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12
  },
  themeToggleTextWrap: { flex: 1 },
  toggleTrack: {
    width: 48,
    height: 28,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: colors.outline,
    backgroundColor: colors.surfaceHigh,
    padding: 3,
    justifyContent: "center"
  },
  toggleTrackActive: { borderColor: colors.primaryOutline, backgroundColor: colors.primaryContainer },
  toggleKnob: { width: 20, height: 20, borderRadius: 10, backgroundColor: colors.text },
  toggleKnobActive: { alignSelf: "flex-end", backgroundColor: colors.onPrimary },
  modalLayer: { flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 20 },
  modalScrim: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.58)" },
  modalCard: {
    width: "100%",
    maxWidth: 440,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.outline,
    backgroundColor: colors.surface,
    padding: 18,
    gap: 14
  },
  modalHeader: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  modalTitleWrap: { flex: 1, gap: 3 },
  modalTitle: { color: colors.text, fontSize: 21, lineHeight: 27, fontWeight: "900" },
  modalCloseButton: {
    width: 38,
    height: 38,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.outline,
    backgroundColor: colors.surfaceGlassHigh,
    alignItems: "center",
    justifyContent: "center"
  },
  modalInput: {
    minHeight: 50,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.primaryOutline,
    backgroundColor: colors.background,
    color: colors.text,
    paddingHorizontal: 14,
    fontSize: 16
  },
  inputError: { color: colors.tertiary, fontSize: 12, lineHeight: 17, fontWeight: "700" },
  modalActions: { flexDirection: "row", alignItems: "center", justifyContent: "flex-end", gap: 10 }
  });
}

export const styles = createStyles(colors);
